branches:
  only:
    - master

sudo: required

git:
    depth: 1

language: bash

services:
  - docker

before_install:
- docker build -t kcyeu/boost .

script:
#- "curl -H 'Content-Type: application/json' --data '{\"source_type\": \"Branch\", \"source_name\": \"master\"}' -X POST https://registry.hub.docker.com/u/kcyeu/agilefant/trigger/de045fe0-bf29-4316-afff-889dafc4ba18/"

